Repository apereo/cas, pull requests merged in 2018-06, with the labels that each got.

#3356 Node upgrade
  gradle.properties
  webapp/gradle/webapp.gradle
  webapp/package-lock.json
  webapp/package.json
Labels: Dependencies & Modules, New Feature

#3360 Fix to print all maps in a cache for heath endpoint
  core/cas-server-core-monitor/src/main/java/org/apereo/cas/monitor/AbstractCacheHealthIndicator.java
Labels: Bug, Monitoring & Dashboards

#3367 Make classes more easily overridable by defining protected variables
  support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationAction.java
  support/cas-server-support-pac4j-core-clients/src/test/java/org/apereo/cas/support/pac4j/web/flow/DelegatedClientAuthenticationActionTests.java
  support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsAction.java
Labels: Refactoring & Code CleanUp

#3372 Make classes more easily overridable by defining protected variables
  support/cas-server-support-pm-webflow/src/main/java/org/apereo/cas/pm/web/flow/actions/SendPasswordResetInstructionsAction.java
Labels: Refactoring & Code CleanUp

#3373 [WIP] Experimenting with Travis CI Build Stages
  .travis.yml
  build.gradle
  ci/analyze-dependencies.sh
  ci/analyze-style.sh
  ci/build-config-metadata.sh
  ci/build-javadocs.sh
  ci/build.sh
  ci/download-dependencies.sh
  ci/init-travis-build.sh
  ci/install.sh
  ci/publish-snapshots.sh
  ci/report-dependency-updates.sh
  ci/run-cassandra-server.sh
  ci/run-couchbase-server.sh
  ci/run-couchdb-server.sh
  ci/run-dynamodb-server.sh
  ci/run-influxdb-server.sh
  ci/run-ldap-server.sh
  ci/run-mail-server.sh
  ci/run-memcached-server.sh
  ci/run-mssql-server.sh
  ci/run-mysql-server.sh
  ci/run-postgres-server.sh
  ci/tests/cassandra/run-cassandra-server.sh
  ci/tests/cassandra/run-tests-cassandra.sh
  ci/tests/cosmosdb/run-tests-cosmosdb.sh
  ci/tests/couchbase/run-couchbase-server.sh
  ci/tests/couchbase/run-tests-couchbase.sh
  ci/tests/couchdb/run-couchdb-server.sh
  ci/tests/couchdb/run-tests-couchdb.sh
  ci/tests/dynamodb/run-dynamodb-server.sh
  ci/tests/dynamodb/run-tests-dynamodb.sh
  ci/tests/filesystem/run-tests-filesystem.sh
  ci/tests/ignite/run-tests-ignite.sh
  ci/tests/influxdb/run-influxdb-server.sh
  ci/tests/influxdb/run-tests-influxdb.sh
  ci/tests/ldap/run-ldap-server.sh
  ci/tests/ldap/run-tests-ldap.sh
  ci/tests/mail/run-mail-server.sh
  ci/tests/mail/run-tests-mail.sh
  ci/tests/memcached/run-memcached-server.sh
  ci/tests/memcached/run-tests-memcached.sh
  ci/tests/mongodb/run-tests-mongodb.sh
  ci/tests/mssqlserver/run-mssql-server.sh
  ci/tests/mssqlserver/run-tests-mssqlserver.sh
  ci/tests/mysql/run-mysql-server.sh
  ci/tests/mysql/run-tests-mysql.sh
  ci/tests/postgres/run-postgres-server.sh
  ci/tests/postgres/run-tests-postgres.sh
  ci/tests/redis/run-tests-redis.sh
  ci/tests/run-tests-simple.sh
  gradle.properties
  gradle/overrides.gradle
  gradle/tasks.gradle
  support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/SamlIdPConfigurationTests.java
  support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/GroovySamlRegisteredServiceAttributeReleasePolicyTests.java
  support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/services/PatternMatchingEntityIdAttributeReleasePolicyTests.java
  support/cas-server-support-saml-idp/src/test/java/org/apereo/cas/support/saml/web/idp/profile/builders/response/SamlProfileSaml2ResponseBuilderTests.java
  support/cas-server-support-saml-sp-integrations/src/test/java/org/apereo/cas/util/SamlSPUtilsTests.java
Labels: Build/Release/Packaging

#3371 ChainingPrincipalResolver changes to allow overriding the Principal ID
  core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/principal/resolvers/ChainingPrincipalResolver.java
  core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/principal/PersonDirectoryPrincipalResolverTests.java
  support/cas-server-support-ldap/src/test/java/org/apereo/cas/authentication/principal/PersonDirectoryPrincipalResolverLdaptiveTests.java
  support/cas-server-support-trusted/src/main/java/org/apereo/cas/adaptors/trusted/config/TrustedAuthenticationConfiguration.java
Labels: Improvement, Principal Resolution
