Repository apereo/cas, pull requests merged in 2023-07, with the labels that each got.

#5691 feat: make console and file log patterns consistent and more configurable
  webapp/cas-server-webapp-resources/src/main/resources/log4j2.xml
Labels: Audits & Logging

#5695 docs: there is no "expired device registrations" cleaner for GAuth
  docs/cas-server-documentation/mfa/GoogleAuthenticator-Authentication.md
Labels: Documentation, MFA Google Authenticator

#5694 feat: set `log.console.stacktraces` to `true` by default
  webapp/cas-server-webapp-resources/src/main/resources/log4j2.xml
Labels: Audits & Logging

#5705 Support DN and password for LDAP SASL.
  support/cas-server-support-ldap-core/src/main/java/org/apereo/cas/util/LdapUtils.java
Labels: LDAP & Active Directory, Proposal Declined, Remember: Port Forward, See Contributor Guidelines, Remember: Needs Tests

#5715 add logging to catch time sync issues - 6.6.x
  api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/RootCasException.java
  core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
  core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/InvalidTicketExceptionTests.java
  core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java
Labels: Audits & Logging, Remember: Port Forward, CI

#5716 add logging to catch time sync issues
  api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/RootCasException.java
  core/cas-server-core-tickets-api/src/main/java/org/apereo/cas/ticket/registry/AbstractTicketRegistry.java
  core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/InvalidTicketExceptionTests.java
  core/cas-server-core-tickets/src/test/java/org/apereo/cas/ticket/registry/BaseTicketRegistryTests.java
Labels: Audits & Logging, CI
