Repository apereo/cas, pull requests merged in 2025-02, with the labels that each got.

#6342 Fix throttling CRON keys
  support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/InMemoryThrottledSubmissionCleaner.java
Labels: Authentication Throttling, CI, Under Review, Auto Merge

#6341 Fix throttling CRON keys
  support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/InMemoryThrottledSubmissionCleaner.java
Labels: Authentication Throttling, CI, Under Review, Auto Merge

#6340 Fix throttling expiration
  support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/AbstractInMemoryThrottledSubmissionHandlerInterceptorAdapter.java
Labels: Authentication Throttling, Remember: Port Forward, See Contributor Guidelines, CI

#6368 Fix throttling endpoint deleteByKey
  support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/ThrottledSubmissionHandlerEndpoint.java
  support/cas-server-support-throttle/src/test/java/org/apereo/cas/web/support/ThrottledSubmissionHandlerEndpointTests.java
  support/cas-server-support-thymeleaf/src/main/resources/static/js/palantir.js
Labels: Authentication Throttling, User Interface & Themes, CI, Under Review, Auto Merge

#6367 Fix throttling endpoint deleteByKey
  support/cas-server-support-throttle-core/src/main/java/org/apereo/cas/throttle/ThrottledSubmissionHandlerEndpoint.java
  support/cas-server-support-throttle/src/test/java/org/apereo/cas/web/support/ThrottledSubmissionHandlerEndpointTests.java
  support/cas-server-support-thymeleaf/src/main/resources/static/js/palantir.js
Labels: Authentication Throttling, User Interface & Themes, CI

#6471 Mfa simple bypass rest add headers test
  core/cas-server-core-authentication-mfa-api/src/test/java/org/apereo/cas/authentication/RestMultifactorAuthenticationProviderBypassEvaluatorTests.java
Labels: REST Protocol & Integrations, MFA, MFA Bypass, Unit/Integration Tests, Under Review, Auto Merge
