Repository apereo/cas, pull requests merged in 2025-03, with the labels that each got.

#6491 Fixing OpenFGA check call
  core/cas-server-core-services-api/src/main/java/org/apereo/cas/services/OpenFGARegisteredServiceAccessStrategy.java
  docs/cas-server-documentation/services/Service-Access-Strategy-OpenFGA.md
Labels: Documentation, Under Review

#6646 Faster pattern matching
  support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/discovery/webfinger/OidcDefaultWebFingerDiscoveryService.java
Labels: Under Review

#6647 faster pattern matching
  support/cas-server-support-oidc-core-api/src/main/java/org/apereo/cas/oidc/discovery/webfinger/OidcDefaultWebFingerDiscoveryService.java
Labels: Under Review

#6638 Don't retry failed login attempts in order to avoid premature account locking.
  core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/MockWebServer.java
  support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
  support/cas-server-support-rest-authentication/src/test/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandlerTests.java
Labels: Under Review, Auto Merge

#6657 Don't retry failed login attempts in order to avoid premature account locking
  core/cas-server-core-util-api/src/test/java/org/apereo/cas/util/MockWebServer.java
  support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java
  support/cas-server-support-rest-authentication/src/test/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandlerTests.java
Labels: Remember: Port Forward, Auto Merge
