Repository apereo/cas, pull requests merged in 2025-05, with the labels that each got.

#6852 Preserve map when merging attributes
  core/cas-server-core-authentication-api/src/main/java/org/apereo/cas/authentication/CoreAuthenticationUtils.java
  core/cas-server-core-authentication/src/test/java/org/apereo/cas/authentication/CoreAuthenticationUtilsTests.java
  support/cas-server-support-oauth-api/src/main/java/org/apereo/cas/support/oauth/OAuth20Constants.java
  support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/util/OAuth20Utils.java
  support/cas-server-support-oauth-core-api/src/main/java/org/apereo/cas/support/oauth/validator/CASOAuth20TicketValidator.java
  support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/util/OAuth20UtilsTests.java
  support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/validator/CASOAuth20TicketValidatorTests.java
  support/cas-server-support-oauth/src/test/java/org/apereo/cas/support/oauth/web/OAuth20TicketGrantingTicketAwareSecurityLogicTests.java
Labels: Attribute Resolution, Attribute Release, CI, Under Review, Auto Merge

#6918 Fix: CAS Interrupt Thymeleaf View – Sanitize link ID to handle special characters
  ci/tests/puppeteer/scenarios/interrupt-afterauthn-groovy/interrupt.groovy
  ci/tests/puppeteer/scenarios/interrupt-afterauthn-groovy/script.js
  support/cas-server-support-thymeleaf/src/main/resources/templates/interrupt/casInterruptView.html
Labels: User Interface & Themes, Interrupt Notifications, Unit/Integration Tests, Puppeteer, Under Review, Auto Merge

#6941 Improve logs and fix bug in WebAuthn support
  support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorWebflowConfigurer.java
  support/cas-server-support-webauthn-core/src/main/java/org/apereo/cas/webauthn/web/WebAuthnController.java
Labels: Authentication, Audits & Logging, MFA, CI, Passwordless, Under Review, Auto Merge

#6942 Improve logs and fix bug in WebAuthn support
  support/cas-server-support-webauthn-core-webflow/src/main/java/org/apereo/cas/webauthn/web/flow/WebAuthnMultifactorWebflowConfigurer.java
  support/cas-server-support-webauthn-core/src/main/java/org/apereo/cas/webauthn/web/WebAuthnController.java
Labels: Authentication, Audits & Logging, MFA, CI, Passwordless, Under Review, Auto Merge
